# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'About', url: 'about'}
- {name: 'Projects', url: 'projects'}
- {name: 'Statistics', url: 'statsitics'}
- {name: 'CV', url: 'cv'}
- {name: 'Documentation', url: 'documentation'}
- {name: 'Contact', url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link:  'https://www.linkedin.com/in/milagros-cortez-91074020a'}
- {icon: 'linkedin', link:   'https://github.com/MiliC01'}
- {icon: 'instagram', link:  'https://instagram.com/milic1029'}
- {icon: 'envelope', link:   'mailto:milicortez2445@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
